
# 数据库链接相关信息
address: 'localhost'
port: 3306
database: 'web'
username: 'root'
password: 'A123456789a'

# 服务器模式
# develop 服务器开发模式：可用于使用各种类型的工具
# release 正式模式：生产环境，不会显示debug信息
server-mode: 'develop'

# 游戏相关的配置参数
game:
  # NPC相关的配置
  npc:
    # NPC的出生点方块类型
    spawner-material: 'BEACON'
  # 建筑相关的配置
  building:
    # 建筑材料，建议和矿工挖掘捡起的某样物资一致
    material: 'EMERALD'
    # 是否开启建筑解锁功能
    lock: false
  # 游戏开始时，给玩家的一定的数量
  when-start-give-player: 64
  # 防御塔相关的配置
  turret:
    # 炮口的方块，激光射线会从这个方块发出
    muzzle-material: 'AMETHYST_BLOCK'
  # 每个小组最大玩家数量
  max-group-players: 5
  # 矿物重生时间
  mineral-restore-timer: 10
  # 团队总数，最多6个，最少2个
  max-teams: 3
  # 最少多少个玩家开始游戏
  min-players: 2
  # 游戏开始等待时间（秒）
  waiting-timer: 120
  # 游戏总时长（秒）
  gaming-timer: 1200
  # 游戏结束后多少秒自动关服（秒）
  stopping-timer: 120
  # 出生点所在地图
  spawn-world: 'RTS'
  # 地图的出生点（坐标点），最少数量为队伍数量，可以更多，
  # 需要配合地图设计来选点，地点相隔建议取适中的距离
  # 如果出生点数量少于队伍数量，则会出现两个队伍共享出生点的奇葩情况
  # 格式为：x,y,z 请注意：分隔的逗号是英文的逗号
  # 本配置文件的坐标地址是官方默认地图的
  # 下载地址：https://待完成
  spawn-locations:
    - '155,49,393'
    - '394,49,184'
    - '604,51,148'
    - '910,49,225'
    - '872,49,540'
    - '764,49,814'
  # 怪物阵营的出生点
  monster-spawner: '435,49,841'

  # 墙体的判定高度
  wall-detect-height: 26

# NPC可食用的 Material Name
foods:
  - 'APPLE'
  - 'BREAD'

# 矿工相关配置信息
miner:
  # 矿工会捡起的物品名称
  picks:
    - 'EMERALD'
    - 'APPLE'
    - 'BREAD'

  # 矿工会挖掘的物品名称
  breaks:
    - 'EMERALD_ORE'

# 建筑升级中跳过的方块
upgrade-skip-blocks:
  - "CHEST"
  - "BARREL"
  - "SHULKER_BOX"