
# 数据库链接相关信息
address: 'localhost'
port: 3306
database: 'web'
username: 'root'
password: 'A123456789a'

# 服务器模式
# develop 服务器开发模式：可用于使用各种类型的工具
# release 正式模式：生产环境，不会显示debug信息
server-mode: 'develop'

# 是否开启bungeecord模式
# 如果开启，游戏结束后会自动将玩家传送回大厅服务器
bungeecord: false
# 大厅服务器名称
bungeecord-lobby: 'imc_lobby'

# 奖励结算命令（配合其他插件）
reward-command: 'hermes modify %player% %amount% 岛屿冲突奖励结算'

# 游戏相关的配置参数
game:
  # NPC相关的配置
  npc:
    # NPC的出生点方块类型
    spawner-material: 'BEACON'
  # 建筑相关的配置
  building:
    # 建筑材料，建议和矿工挖掘捡起的某样物资一致
    material: 'EMERALD'
    # 是否开启建筑解锁功能
    lock: false
  # 游戏开始时，给玩家的一定的数量
  when-start-give-player: 64
  # 防御塔相关的配置
  turret:
    # 炮口的方块，激光射线会从这个方块发出
    muzzle-material: 'AMETHYST_BLOCK'
  # 每个小组最大玩家数量
  max-group-players: 5
  # 团队总数，最多6个，最少2个
  max-teams: 2
  # 2个队伍以上时，是纯PVP还是PVPVE
  multiple-game-mode: 'PVPVE'
  # 最少多少个玩家开始游戏
  min-players: 2
  # 游戏开始等待时间（秒）
  waiting-timer: 120
  # 游戏总时长（秒）
  gaming-timer: 1200
  # 游戏结束后多少秒自动关服（秒）
  stopping-timer: 120
  # 出生点所在地图
  spawn-world: 'RTS'
  # 地图的出生点（坐标点），最少数量为队伍数量，可以更多，
  # 需要配合地图设计来选点，地点相隔建议取适中的距离
  # 如果出生点数量少于队伍数量，则会出现两个队伍共享出生点的奇葩情况
  # 格式为：x,y,z 请注意：分隔的逗号是英文的逗号
  # 本配置文件的坐标地址是官方默认地图的
  # 下载地址：https://待完成
  spawn-locations:
    - '-75,87,-170'
    - '-75,87,156'
#    - '155,49,393'
#    - '394,49,184'
#    - '604,51,148'
#    - '910,49,225'
#    - '872,49,540'
#    - '764,49,814'
  # 怪物阵营的出生点（大于等于3个团队时生效）
  monster-spawner: '435,49,841'
  # 等待大厅世界
  lobby-world: 'lobby'
  lobby-location: '0.5,65,0.5'

  # 墙体的判定高度
  # wall-detect-height: 26
  wall-detect-height: 84
  # 桥的虚空判定高度
  bridge-detect-height: 73

# NPC可食用的 Material Name
foods:
  - 'APPLE'
  - 'BREAD'

# 矿工相关配置信息
miner:
  # 矿工会捡起的物品名称
  picks:
    - 'EMERALD'
    - 'APPLE'
    - 'BREAD'

  # 矿工会挖掘的物品名称
  breaks:
    - 'EMERALD_ORE'

# 建筑升级中跳过的方块
upgrade-skip-blocks:
  - "CHEST"
  - "BARREL"
  - "SHULKER_BOX"

# 游戏内公告
# 公告间隔时间
notice-interval: 20
# 公告消息内容
notice:
  - '&7战局内默认队内聊天，如果需要全局聊天，请使用 &c/all <聊天消息>'
  - '&7游戏目标是&c摧毁敌方大本营&7，或者游戏时间结束前&e团队积分大于敌方团队'
  - '&7手中的建筑蓝图是用来建造建筑，并产生NPC的，不要再自己去挖矿了，把这种苦差事交给NPC去做吧！'
  - '&c铁匠铺&7一定要多升级，他那可有不少好东西'
  - '&7攻击型的防御塔的&c建造数量上限等于大本营的等级&7来的，一定要记得升级大本营'
  - '&7右侧计分板的&a绿宝石&7是大本营的箱子里面现存的绿宝石数量，记得拿去用哦'
  - '&7游戏前期一定要多造矿场，尽量把所有矿场都升到满级，满级矿工挖一个绿宝石矿，会掉落&a30个绿宝石！'
  - '&7防空塔的攻击半径是50格距离,3级几乎可以瞬间秒杀在天上的敌人哦~'
  - '&7桥可以在很多地方建造,小心敌人从四面八方过来拆你的基地哦!'
  - '&a小提示:蹲下对着战士按右键,可以让战士跟着你走哦~'
  - '&f防空塔,兵营,修复塔迎来了史诗级的加强~'
  - '&f可以敲自己家的建筑给建筑回血!~'
  - '&c请注意:新版本移除了积分判定胜负的条件,改为基地血量最多的队伍获得胜利!!!积分会在正式版本当中结算给玩家用于购买皮肤等用途,请注意调整战略!~'