name: COIRealm
main: com.mcylm.coi.realm.Entry
api-version: 1.17
version: 1.0
author: Mikesam
website: https://www.clayun.com
depend: [helper]
commands:
  structure:
    description: save building structure
    usage: /<command> save fileName