name: COIRealm
main: com.mcylm.coi.realm.Entry
api-version: 1.18
version: 1.0
author: Mikesam
website: https://www.mcylm.com
depend: [helper,Citizens]
commands:
  structure:
    description: save building structure
    usage: /<command> save fileName
  cdebug: